### ISSUE TITLE
dev-app: no media on stage, but in studio media items show as assigned

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#910] opened 2022-05-03 16:23 UTC
on dev-app,  Schildbrau-20, there is no media on the demo stage. in the stage management media list there is also no media showing as assigned to this stage. 
but in the studio, it is showing the sample media for new installs, as being assigned to the demo stage.
(actually there are 2 demo stages in the dropdown list in the studio - one shows the sample media; the other shows nothing)
if i click on the demo stage link in the studio, i enter the stage as audience - no tools - but showing as logged in player in the counter.
if i enter the stage from the Backstage stages list, i have the tools, but there is no media in any of the tool bars. 
![Screenshot from 2022-05-03 18:19:27](https://user-images.githubusercontent.com/3437324/166494243-6f3adafe-bfa7-421c-aa5b-2fac2c898c06.png)

![Screenshot from 2022-05-03 18:18:39](https://user-images.githubusercontent.com/3437324/166494248-fe2cff8a-7a9e-4fc3-88e2-8f3c0927424b.png)

**Comment by nguyenhongphat0** [comment] 2022-05-03 16:42
OMG you're so fast 🤣 

As explained before: There was 2 Demo stage. The Demo stage that the curtain is assigned to doesn’t have any players, so you are an audience. And audiences does not see the player tools. The other have you as a player, but doesn’t have the curtain assigned with, that’s why you don’t see it!

<img width="1362" alt="Screen Shot 2022-05-03 at 23 34 52" src="https://user-images.githubusercontent.com/29925961/166499828-90a2401d-de8c-484a-a9a5-ce31f7b61437.png">

I changed the name of these stage to make things less confusing, and add you as player of the Demo stage. This is not a bug!

<img width="1438" alt="Screen Shot 2022-05-03 at 23 40 06" src="https://user-images.githubusercontent.com/29925961/166499706-2883c113-42ae-41d6-8919-e1678c0e36d1.png">

**Closed by nguyenhongphat0** 2022-05-03 16:42 UTC
Labels: bug, stage, studio

**Comment by nguyenhongphat0** [comment] 2022-05-03 16:47
In case you wondering why there were 2 Demo stages: I cloned the demo stage to make more stage on the foyer to do the masonry grid layout! It's not another weird bug 😅

**Comment by helenvarley** [comment] 2022-05-04 07:32
> OMG you're so fast rofl
> 
and this in the middle of doing a funding application ... just call me lightning :zap:
