### ISSUE TITLE
prop i uploaded says it was uploaded by phat

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#751] opened 2022-01-14 15:02 UTC
i have just uploaded 3 props, one of which is fine, one is not visible anywhere and the other is there but showing as uploaded by phat and with a different name to what i gave it when i uploaded it.
there is also no edit button for this prop.
![Screenshot from 2022-01-14 16:02:20](https://user-images.githubusercontent.com/3437324/149537038-52a26cb5-5edc-488e-a5ad-0f4c799bb0a1.png)

**Comment by nguyenhongphat0** [comment] 2022-01-15 09:44
Wow that was insane 🥶

**Comment by helenvarley** [comment] 2022-01-15 12:57
yes, some ghost in the machine i think! :laughing:

**Comment by helenvarley** [comment] 2022-01-15 13:01
also with many of the media items that are showing as uploaded by phat (on upstage.live), i cannot edit them - for example my own helen avatar (should i make a separate issue for this?). not sure if it's the same on dev-app. it might be media items uploaded before a certain time?

**Comment by helenvarley** [comment] 2022-01-15 13:03
also i think the avatar that previously had the name VicPalace (which this prop now has) has disappeared from upstage.live - it seems i may have somehow replaced that av with the blue hair, when i was uploading the blue hair as a prop ... ???

**Comment by vickis** [comment] 2022-01-16 04:23
wow crazy bug! you win on that one :D

VicPalace was my av from back in the graphical chat space days  - spikey
dark hair, glasses and a green outfit

many of the earlier avs etc that I uploaded were latter seen as uploaded by
Phat - i _think_ in the transition between some of the very early
iterations (especially when we had a dev and 'open' UpStage)

however they were usually editable, able to be assigned to stages and all
the expected behaviours

[image: image.png]

could this have anything to do with you putting a use restriction on the
media?

**Comment by helenvarley** [comment] 2022-01-17 09:20
yes i also noticed that some media i'd uploaded changed to be uploaded by phat - i think this happened a while back with one of the releases? 
i don't know if the use with acknowledgement had anything to do with it - i uploaded other things successfully also with these permissions.
teething issues with the studio maybe? i notice a few inconsitencies between the media list in the stage management section and what we see in the studio, maybe these will get worked out as the old system is completely replaced?

**Comment by vickis** [comment] 2022-01-17 09:27
ok yes understand about the uploaded by Phat that happened in a very early
new version (across media)
VicPalace was one of the ones that came to be renamed as uploaded by Phat
a common thing between that and the wigs uploads was you had recently been
holding VicPalace - otherwise it seems a random thing to choose

v weird bug :)

**Comment by nguyenhongphat0** [comment] 2022-01-17 14:38
Yes this is the most weird bug I've ever seen (and made) :sweat_smile: I'm working on it and fix it as soon as I can, sorry!

**Comment by helenvarley** [comment] 2022-01-17 14:48
have you been able to replicate it?

**Comment by nguyenhongphat0** [comment] 2022-01-17 15:05
Yes when I upload something it always show uploaded by Phat :laughing: I'm trying to replicate it with account `demo`, but the bug haven't occur yet!

**Comment by helenvarley** [comment] 2022-01-17 15:14
i just uploaded another prop, i set the permissions to use with acknowledgement (as i did with the wig) & it has uploaded as expected, showing me as the uploaded ... maybe it was some weird temporary glitch??

**Comment by gloriajw** [comment] 2022-01-17 15:21
This usually only happens in two cases: (1) the back end endpoint isn't using the proper JWT token to verify the user before running, or (2) the back end is caching something it should not be caching, and 'session bleed' is happening. Making sure (1) is right is supposed to prevent (2) from happening.

**Comment by nguyenhongphat0** [comment] 2022-01-17 15:34
I just check (1) and I can confirm JWT token and user_id of the owner are correctly set. (2) could be the cause, since Studio use Apollo to perform graphQL query and mutations, and apollo has it own caching system! 

Looking for VicPalace I found 2 versions of him, and none of them are the blue wig :thinking: 
![image](https://user-images.githubusercontent.com/29925961/149798462-934b389b-3de7-4c2a-8fda-8de2220f816d.png)

**Comment by nguyenhongphat0** [comment] 2022-01-17 15:39
Is that the blue wig that you had tried to upload, Helen? Look like the bug is the uploaded media not correctly show up after upload, because media's info are still saved successfully!

![image](https://user-images.githubusercontent.com/29925961/149798908-a624b995-a48b-44b2-9c44-cba63c558123.png)

**Comment by helenvarley** [comment] 2022-01-17 15:58
i re-uploaded the blue wig
the VicPalace avatar is a different one to the VincentPalace av - it is in a green outfit. it seems to have disappeared completely from the server (at least, i could not find it after this bug happened) so i think my blue wig replaced it. but then i had to reupload the blue wig so that i could edit it, as there was no edit button showing for me for the blue wig that appeared to be uploaded by phat and replacing VicPalace ...

**Comment by helenvarley** [comment] 2022-01-17 16:00
this is VicPalace:
![image](https://user-images.githubusercontent.com/3437324/149802547-03f5d720-f38c-4dc3-b50f-32d3affd4095.png)

**Comment by nguyenhongphat0** [comment] 2022-01-17 16:08
Thank you for the information. If you have any details about this, please let me know :pray: I'm still trying to replicate this

>  as there was no edit button showing for me for the blue wig that appeared to be uploaded by phat

If that prop was uploaded by me and the permission is set to `Use with acknowledge`, you have to click on the 
:ballot_box_with_check: Acknowledge button to confirm that you're acknowledge of using the media created by me. After that these buttons will appear. Do you still remember this flow: [#547](https://github.com/upstage-org/upstage/issues/547#issuecomment-981094144)? :sweat_smile:

**Comment by helenvarley** [comment] 2022-01-17 16:15
aaaah i forgot about that!

**Comment by helenvarley** [comment] 2022-01-17 16:19
ok, nearly all the media on upstage.live is showing as copyright free, because it was uploaded before the system was there. & the ones that are not copyright free are all uploaded by me, so the edit button is there ... but i found VicPalace and ticked the box and now i see the edit button :)

actually, i wanted to see what the tickbox looked like before i ticked it, because i think it was showing kind of like it was ticked already?? but now i cannot get rid of the edit button ! :laughing:

**Comment by nguyenhongphat0** [comment] 2022-02-20 12:43
I tried so many times but could not re-produce this issue. However studio just got a dependencies version upgrade that includes a caching improvement of Apollo, which could be the case of this weird issue. I will mark this as closed, feel free to re-open it when you experience the issue again. Thank you :pray:

**Closed by nguyenhongphat0** 2022-02-20 12:43 UTC
Labels: bug, studio

**Comment by vickis** [comment] 2022-02-20 18:20
Thanks Phat
it feels like a legacy from that original few instances where the avatars
etc that we had uploaded all ended up tagged to you (some are still listed
as that)
i agree close for now :)
