### ISSUE TITLE
should not be possible to have same email address for more than one account

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1089] opened 2023-04-27 22:35 UTC
vicki has just created a user account for someone who already had an account, using the same email address that the original account was created with. it should not be possible for there to be two different users with the same email address - this will be confusing for players if they log in with one account and expect to find the media and stages of another account.

if someone attempts to create an account with the same email address as is used with an existing account, there should be a message saying this account already exists and suggesting they use the forgot password tool if they don't remember how to access the existing account.

**Comment by vickis** [comment] 2023-05-09 20:35
I am comfortable with it for testing
It has arisen because artists forget their logins and don’t use forgot
password function
We
Could do more work on making sure there aren’t double ups (I was
responsible for the last one sorry )

It does seem for new installs / hosted instances that the single email
allowance would be best used :)

**Comment by helenvarley** [comment] 2023-05-22 01:16
what's the standard scenario for this? i thought that in most situations where i am creating an account on a platform, i cannot create a new account with the same email address that is already attached to an existing account. so there must be some way that this is handled for testing.
i don't think there are too many duplicates at the moment. it shouldn't take too much time for vicki & i to check them & work out what can be deleted. so as long as there is a workable testing process then i would be in favour of having it set so that it's not possible to create a new account with the same email that already has an account.

**Comment by gloriajw** [comment] 2023-05-22 17:19
Standard scenario for this is to de-dup the existing emails for existing accounts, then add a unique index to prevent it from happening in the future. This will turn this feature OFF everywhere, for testing and on publicly accessible servers.

**Comment by vickis** [comment] 2023-05-22 20:39
sounds reasonable and interested in your advice here devs
I have two accounts for testing purposes (however i have a couple of emails
which i use for this )

The issue is mainly artists forgetting they have logins or that they can
use forgot password etc to retrieve their original accounts

**Comment by helenvarley** [comment] 2023-05-27 02:26
happy to go with the standard. would there be a message, in the case of trying to create a new account with an existing email, saying that this email address already has an account?

**Comment by gloriajw** [comment] 2023-05-27 02:27
Yes.

**Comment by teddyfullstack** [comment] 2023-07-17 13:57
Hi guys, it's good to be back 🤗 
I'm working on this issue now 💪

**Comment by gloriajw** [comment] 2023-07-17 14:13
Welcome back!

**Comment by vickis** [comment] 2023-07-17 20:22
great thanks :D

**Comment by helenvarley** [comment] 2023-07-21 04:41
reopening this because when i tested it, i didn't get an error message for the duplicate email. here's what i did:

- from Player Management, i went to Batch User Creation and created a new user called testy.
- i then went to the edit profile for that user, & entered my own email address, which already belongs to my account on dev-app. 
- i clicked Update Information, & got the message "player information updated successfully!" - but in the player list, no email showed, and when i opened the profile my email address was not there.

what i should have seen is a message saying "This email address already belongs to another user" (or something similar)

**Comment by teddyfullstack** [comment] 2023-07-23 10:07
I forgot that emails can be updated from there too. PR #1089 fixed it 👇 

<img width="466" alt="Screenshot 2023-07-23 at 16 54 48" src="https://github.com/upstage-org/upstage/assets/29925961/d010a279-4ea4-4e5c-b7c8-57f394c5858b">

P.S: actually, the unique constrain already making sure there won't be 2 users with the same email address, what we were missing is a properly error message 😅

**Comment by helenvarley** [comment] 2023-07-28 00:06
ok, so i tested it again, & this time i got the error message telling me that the email already belongs to another user (great!) ... BUT ... when i returned to the Player list, there was the test user with my email address showing in the list.
i've left that account there at the moment (username testing email) so that you can see, it is still displaying the same email address as my helen username.

**Comment by teddyfullstack** [comment] 2023-07-28 13:51
It was my bad to design these tables so reactive to changes, even those which weren't saved 🤦  But the good things is @heluDuyne and I are working on migrating all of these into Studio, which we will discuss further in #1083. Let's close this issue now because the email unique constrains is resolved 👌

**Comment by gloriajw** [comment] 2023-07-28 13:56
Sounds good to me!

**Comment by gloriajw** [comment] 2023-07-28 13:57
Closing this issue, front end issue only at this point. Will be handled in https://github.com/upstage-org/upstage/issues/1083

**Closed by gloriajw** 2023-07-28 13:57 UTC
Labels: access control, backstage
