### ISSUE TITLE
streaming - any potential in chatmosphere?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#877] opened 2022-04-09 16:26 UTC
one of the projects presented at the FOSSASIA lightning talks was Chatmostphere: 
https://chatmosphere.cc/
https://github.com/Chatmosphere/

it's based on jitsi & has similarities to another chat platform wonder.me, in that your webcam image is round and you can move it around the screen; when you come closer to another person their volume increases, and when you move away from them it decreases. the idea is to make it more like a room where you can move from one group to another, & just hear the conversation that you are closest to.

i don't think the volume increase/decrease feature is so appropriate for us but the possibility to have the webcams moveable and not trapped in the jitsi frame would be cool. i guess embedding chatmosphere instead of jitsi would still contain the webcams within that embed frame, but if you made the frame the size of the stage it could be interesting. also it does not have the same controls popping up that the jitsi window has so maybe possibilities to limit who can open their cam/mic if we want to use in performance ... ????

@gloriajw what do you think, does it look like there could be possibilities for UpStage with this? it's been developed during the pandemic lockdowns by a german couple. if you think there is  potential i could contact them & see if they are interested in maybe collaborating.

**Comment by vickis** [comment] 2022-04-09 19:54
Seems interesting - maybe the webcams are using object controls like very
thing on upstage (or proximity awareness but what happens with the layering
could avatars or props moe between the floating webcam bubbles
I wonder if it could end up be hard to isolate and track each element

it could be interesting to test ... but also is it just cluttering up the
stage with stuff and allowing the potential for audiences to just zoom
around .. I am losing the sense of story crafting and theatre to bells and
whistles ...
perhaps is my minimal aesthetic ;) and joy at how well the current stages
load and work

**Comment by helenvarley** [comment] 2022-04-10 10:45
what i am wondering is, if this might allow us to hide the tools so that we can limit and control when audience can show/mute their cams & mics.
also i would expect that the moveable webcams would still be contained within the embedded object, as it is now - the jitsi window is the object, not the webcams. so i am imagining that you would be able to move your webcam within the frame of the chatmosphere object.
but i do not know enough about how it works, this is just my wonderings :smile:

**Comment by vickis** [comment] 2022-04-10 17:29
Ah yes good point  :)

**Comment by nguyenhongphat0** [comment] 2022-04-11 16:27
Thanks to the open source code of [chatmosphere.cc](https://chatmosphere.cc/), I can dig in to find how they able to embedding each user web cam into a single object, instead of embedding the whole chat room. I guess they are using a deeper system level of Jitsi Videobridge.

**Comment by nguyenhongphat0** [comment] 2022-04-11 16:30
Integrating low level API (like chatmosphere is doing) would take a lot of works than embedding a whole chat room. So this won't be able to finish in these upcoming releases yet, just to let you know 😅

**Comment by vickis** [comment] 2022-04-11 19:06
It’s ok phat it’s a bought exercise
if it’s too much work, perhaps it requires  some more thinking about its
potential uses by the artists (and us) :)

**Comment by helenvarley** [comment] 2022-04-11 20:12
> It’s ok phat it’s a bought exercise 
who bought the exercise? :rofl:

**Comment by vickis** [comment] 2022-04-11 20:28
you bought the thought exercise - i brought the thinking about it being a
potential for more exercise than the dev team need at the moment ;)
(sorry for the fraught nature of the english language team!! :)

**Comment by nguyenhongphat0** [comment] 2022-05-29 15:42
> Integrating low level API (like chatmosphere is doing) would take a lot of works than embedding a whole chat room. So this won't be able to finish in these upcoming releases yet, just to let you know 😅

Sorry for keep you waiting, the feature is finally here. But it still have random issue with voice "echoing" and lack of options (I'm working on it 😅)

<img width="1300" alt="Screen Shot 2022-05-29 at 22 17 08" src="https://user-images.githubusercontent.com/29925961/170878129-cd16529c-ddf7-4bb4-ae5e-ec7da4c65152.png">

**Comment by helenvarley** [comment] 2022-05-29 16:34
wow @nguyenhongphat0 this looks amazing! does it mean that we can have separate jitsi webcams & move them around? is it on dev-app yet? i guess i can't test it on my own, because then i only have my cam anyway. vicki & i are meeting with sara & eva on tuesday & could try it then, if it is ready to play with.

**Comment by vickis** [comment] 2022-05-29 20:10
super Phat :)

**Comment by nguyenhongphat0** [comment] 2022-05-30 14:42
> does it mean that we can have separate jitsi webcams & move them around

Yes, of course 😆 

> is it on dev-app yet?

It's on `dev-app1` now!

**Comment by nguyenhongphat0** [comment] 2022-05-30 14:44
I'll close this issue and open another for the next things to do with the low level integration (since this issue is more like a discussion and it's already very long 😅 )

**Closed by nguyenhongphat0** 2022-05-30 14:44 UTC
Labels: enhancement, question, streaming

**Comment by gloriajw** [comment] 2022-05-30 14:55
@helenvarley @vickis if this works as intended and you OK all other functionality currently on dev-app1, I'll cut another release so we can roll this out to production environments.

**Comment by helenvarley** [comment] 2022-05-30 15:26
i haven't been able to test it yet as need more than one person. i have 2 meetings with vicki tomorrow so hopefully will get a chance to try it out on dev-app. exciting!!!
