### ISSUE TITLE
Permission system email notifications

### ISSUE THREAD

**Issue by teddyfullstack** [upstage-org/upstage#790] opened 2022-02-23 15:24 UTC
Is it possible for the system to send an email, both to the player who is being asked for approval and then to the other player when the request has been approved or denied? it could be a generic message saying you have a notification on UpStage, please look. (this would be useful for all of the permissions system)

Separated issue from: https://github.com/upstage-org/upstage/issues/787#issuecomment-1048890819

**Comment by helenvarley** [comment] 2022-05-05 19:37
this will be very helpful! :)

**Comment by vickis** [comment] 2022-05-05 20:38
this is great yes :)

**Comment by helenvarley** [comment] 2022-05-10 14:30
just reopening this because of a couple of issues:
- when i tested it, it worked fine until i tried to approve the request - then some error message appeared at the top of the screen. unfortunately it disappeared before i could screengrab it. but it did work, to approve the request.
- it's really great to get the email saying that there is a request waiting to be approved - this is super helpful. can there also be an email sent to the person who requested permission, letting them know that their request has been approved or denied?
- the other issue is a bigger one, & i guess should be a separate issue: now that my other account has permission to use this media, it's in fact given full permission - meaning that the person who has received permission to use the media can also now change the ownership and give or revoke permission for this media from other players. this should not be possible. they should only have access to use the media item on a stage, not to edit it in the studio.

**Comment by vickis** [comment] 2022-05-10 17:24
Te the last point - this is perhaps a chance to make a copy to edit and
reshape - opensource the media also :)

**Comment by helenvarley** [comment] 2022-05-10 19:47
but if you want your media to be available for others to use as they like, then you leave the permissions as copyright free. then any other player can use it and edit it. if you've chosen to require permission it's presumably because you don't want all & sundry to be able to do that.

**Comment by vickis** [comment] 2022-05-10 20:02
Hmm Ye the issue is to use or to modify
Mostly I am fine with all media being shared
It edited is different
I guess it’s more like share with some restrictions and permissions
required to edit ...

**Comment by helenvarley** [comment] 2022-05-11 08:45
with the current system, leaving a media item as the default copyright free means that it can be shared & edited, so you don't need to do anything.

it's the next 2 levels that we need to think about:
- currently "use with acknowledgement" also allows others to edit a media item. there is now the notes field on the edit interface that can specify how you want the media item to be acknowledged - but of course, others can currently also edit this field, so they can potentially remove or change whatever notes you have put here.
- "use with permission" is the same, except that the other player has to request access, so you can choose who to allow access to and revoke it if you want. but once they have access, they can also edit your notes and anything else about the media item.

suggestions:
- only the owner of a media item can edit the Permissions tab (this includes changing the owner, changing the giving and revoking permission, and editing the Notes)
- move the Notes field up above the player list, so that it's more prominent and noticeable for others who need to read it (could it even appear at the top of the edit interface across all tabs as text, & the field on the permissions tab is just for editing it?)

if a player requests access to a media item and you don't mind them using it but you don't want them to have edit access, instead of giving them permission you can just assign it to their stage for them. then they can use it as a player on that stage but not have access to edit it.

**Comment by vickis** [comment] 2022-05-11 09:38
yes agree
greatest suggestions :)

**Comment by fuyloon2018** [comment] 2022-12-07 07:52
> just reopening this because of a couple of issues:
> 
> when i tested it, it worked fine until i tried to approve the request - then some error message appeared at the top of the screen. unfortunately it disappeared before i could screengrab it. but it did work, to approve the request.
> it's really great to get the email saying that there is a request waiting to be approved - this is super helpful. can there also be an email sent to the person who requested permission, letting them know that their request has been approved or denied?
> the other issue is a bigger one, & i guess should be a separate issue: now that my other account has permission to use this media, it's in fact given full permission - meaning that the person who has received permission to use the media can also now change the ownership and give or revoke permission for this media from other players. this should not be possible. they should only have access to use the media item on a stage, not to edit it in the studio. so you really only need to be able to assign it to a stage.

Hi @helenvarley  the first and the last one I can not reproduce it on dev-app1, I will implement the second one

**Comment by fuyloon2018** [comment] 2022-12-08 15:40
> - when i tested it, it worked fine until i tried to approve the request - then some error message appeared at the top of the screen. unfortunately it disappeared before i could screengrab it. but it did work, to approve the request.
@vickis  On dev-env still have this bug above ??

**Comment by vickis** [comment] 2022-12-08 19:43
working as expected
approval message remained for long enough to read and understand
thanks! :D

**Comment by helenvarley** [comment] 2022-12-11 08:59
i received a permissions request email, from player2018 wanting to use my media typing (audio). the email tells me to go to the studio and click on the notifications icon to approve or deny the request, but when i do that, there are no notifications.
when i go to edit the media item, i see that the permissions are set to "use with acknowledgement". this doesn't require me to give permission, which is what the email says.
the email should say "Player2018 has indicated that they wish to use your media item typing and will acknoweldege it as you have specified."

**Comment by helenvarley** [comment] 2022-12-11 20:10
just noticed that there are some guest accounts on dev-app that did not enter an email or a reason for requesting an account - i thought those fields were required?

**Comment by fuyloon2018** [comment] 2022-12-12 03:29
@helenvarley I think we do not need to make an email field is required because a GUEST account cannot enter the studio or backstage

**Comment by fuyloon2018** [comment] 2022-12-12 03:44
> it's really great to get the email saying that there is a request waiting to be approved - this is super helpful. can there also be an email sent to the person who requested permission, letting them know that their request has been approved or denied?

@helenvarley  do we need to send mail notifying the request sender "Your request has been approved"?

**Comment by vickis** [comment] 2022-12-12 03:49
Yes - this will be a useful process because;
a. we can welcome newcomers and indicate things they might want to view or
join (coming shows or walkthrough events :)
b. deny approval (for example if they appear to be a bot we could ask for
more information about why they wish to have an account etc

**Comment by helenvarley** [comment] 2022-12-12 08:58
sorry i should not have put that question about the guests not having email addresses in this issue, it is a separate one (& let's not worry about it right now because normally when someone is making an account they are wanting to be a player, guests is more for waklthroughs & then we make the account).

@vickis  this issue is about the email notifications for the permissions system, not for new accounts. sorry for creating confusion.

@fuyloon2018 - yes, the request sender should get an email notifying them of their request being approved or denied.

**Comment by fuyloon2018** [comment] 2022-12-19 11:30
hi @helenvarley , hi @vickis 

I did: 
- Send mail notifications to Players when they want to use media
- Fix bug sending mail notifications to Owner when other players are using his/her media in acknowledgment mode
Please help me review those on dev-app1
thanks.

**Comment by vickis** [comment] 2022-12-19 20:48
I appear to have been able to add two media items (one with acknowledgement
and one that should have requested permissions) without trouble (however i
was using a recently created login to test

@helen when you are free perhaps you could try adding the  Matariki
backdrop and jupiter prop to better test

thanks :)

**Comment by vickis** [comment] 2022-12-19 20:56
I added the items in the create new stage process - on going into the studio I see all the permissions options (and have requested permission of a couple and acknowledged others - beautiful work @fuyloon2018 :)
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4249450/208522278-113d0ebe-598f-48af-b3d8-e5f24876f7a9.png">


<img width="1231" alt="image" src="https://user-images.githubusercontent.com/4249450/208521990-d263bd49-e2b0-4f18-bed9-1e74374fe2e5.png">

**Comment by vickis** [comment] 2022-12-19 21:08
apologies - I spoke too soon! - the emails have come from the studio interface  

<img width="943" alt="image" src="https://user-images.githubusercontent.com/4249450/208522690-669cc407-24b1-4dd8-99c5-b500495f8da1.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/4249450/208522884-8ea0a89f-668b-4309-ad01-991518ed149d.png">
typo here = want to use yout media  - should be your

..from email:
viva has indicated that they wish to use your media birchwoodMatariki.jpg and will acknoweldege it as you have specified. 
Purpose: None (there is no option to add a purpose this field could be removed here)
typo also in - acknowledge -

<img width="929" alt="image" src="https://user-images.githubusercontent.com/4249450/208522606-bbc72a7f-6e96-40c2-81e5-ebd54f0d037e.png">

Please wait for permission (instead of approve) 

thanks for your great work!

**Comment by helenvarley** [comment] 2022-12-20 01:49
testing:
- i recieved an email advising me that viva has requested permission to use my clock media. i clicked on the link in the email and this brought me to the Studio, where i saw the red icon on the notifications icon. i clicked on "Approve". :+1: 
- requested permission from fuyloon2018 to use avatar aaa. the request button has changed to a message telling me to wait for the media owner's approval :+1: 
- clicked on the "use with acknowledgement" button for vicki's birchwoodMatariki.jpg; now i have the edit button there, but i don't find in the edit interface any instructions about how to acknowledge it (this is not a bug, it's a user thing - we need to encourage people to enter this info - maybe a pop-up when you set a media item to "use with acknowledgement", saying something like "Don't forget to add instructions in the notes field about how you want this media to be acknowledged.")

**Comment by helenvarley** [comment] 2022-12-20 01:51
regarding the "Purpose" field - in the email i got requesting permission for the clock, for the "Purpose" it says "hey testing permissions" - so this is working & it's good to have. 
perhaps this field should be required?

**Comment by helenvarley** [comment] 2022-12-21 01:47
further to my testing yesterday:

- i received a nice email saying my request had been sent to the owner, "please wait to approve" - it would be more correct to say "please wait for their approval" (because it is not me who needs to approve it).
- and the next email informed me that the owner has given permission 😄 
- i went to the studio & looked for the media aaa that i now have permission to use - & couldn't find it; maybe @fuyloon2018 you changed the name and the permissions? i see aaa111 with permissions set to "use with acknowledgement". 
- i don't have any new notifications in the Studio - i expected to see a notification there the same as the email giving permission. would that not make sense?

**Comment by vickis** [comment] 2022-12-21 01:52
The aaa media was requested by me in testing :)
so in fact you got an email that must have cc'd to info@ or support@

[image: image.png]

**Comment by fuyloon2018** [comment] 2022-12-22 06:53
> apologies - I spoke too soon! - the emails have come from the studio interface
> 
> image
> 
> image
> 
> typo here = want to use yout media - should be your
> ..from email:
> viva has indicated that they wish to use your media birchwoodMatariki.jpg and will acknoweldege it as you have specified.
> Purpose: None (there is no option to add a purpose this field could be removed here)
> typo also in - acknowledge -
> 
> image
> 
> Please wait for permission (instead of approve)
> 
> thanks for your great work!

Hi @vickis I  fixed that. you can check it on dev-app1

**Comment by fuyloon2018** [comment] 2022-12-22 07:06
> - i received a nice email saying my request had been sent to the owner, "please wait to approve" - it would be more correct to say "please wait for their approval" (because it is not me who needs to approve it).
I have changed it to "please wait for permission."

> - i went to the studio & looked for the media aaa that i now have permission to use - & couldn't find it; maybe @fuyloon2018 you changed the name and the permissions? i see aaa111 with permissions set to "use with acknowledgement".
I have changed that for self test make sure it sends the right mail to the right person

> - i don't have any new notifications in the Studio - i expected to see a notification there the same as the email giving permission. would that not make sense?
Do mean to have a notifications in acknowledgement mode on the studio interface?

**Comment by helenvarley** [comment] 2022-12-22 09:26
> The aaa media was requested by me in testing :) so in fact you got an email that must have cc'd to info@ or support@ [image: image.png]
> […](#)

no i requested it - see my post above

**Comment by helenvarley** [comment] 2022-12-22 09:34
> > * i don't have any new notifications in the Studio - i expected to see a notification there the same as the email giving permission. would that not make sense?
> 
> Do mean to have a notifications in acknowledgement mode on the studio interface?

i expected to see something in the notifications dropdown, in the top right corner of the studio where the little megaphone icon is. previously something appeared there when there was something happening, it might have been when someone had requested permission for one of my media items. i got an email and there was also a notification in the Studio, so i thought there would be a similar notification there when i received permission.

**Comment by helenvarley** [comment] 2023-11-08 16:22
i am not sure if this has been done? it's difficult to test on dev-app because nearly all the media there has been uploaded by me, & i can't find something uploaded by someone else that isn't copyright free ...

@vickis could you please upload a media item & set its permissions to something other than copyright free (except not shared) & then we can test the system. also i've set the file "test video" to use with acknowledgement so can you try testing that one?

**Closed** 2024-03-04 16:50 UTC
Labels: prioritize, studio
