### ISSUE TITLE
backdrop replaced instead of new backdrop created

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#861] opened 2022-03-28 14:28 UTC
i am trying to upload several backdrops, to meta.upstage.live. the first one uploaded fine, but now whenever i upload another, it simply replaces the previous one.
![backdrop_replaced](https://user-images.githubusercontent.com/3437324/160420434-83124860-69a4-4108-b19f-275f0c0d0eda.gif)

**Comment by helenvarley** [comment] 2022-03-28 14:37
i went out of the studio and back in again, then uploaded a backdrop and it worked as expected. then i waited for a bit and uploaded another, it also worked as expected.

**Comment by nguyenhongphat0** [comment] 2022-04-02 17:19
> i went out of the studio and back in again, then uploaded a backdrop and it worked as expected. then i waited for a bit and uploaded another, it also worked as expected.

The issue is quite hard to replicate because it only happen if you upload a media > open another media to edit and save > upload another one. It got fixed in pull request #866 , and will be available on `dev-app1` as soon as it got approved! Sorry for the inconvenience 😅

**Comment by vickis** [comment] 2022-04-02 18:27
No problem phat - awesome work as usual :)

**Closed** 2022-04-03 03:51 UTC
Labels: bug, backdrops, studio

**Comment by vickis** [comment] 2022-10-11 07:12
so this is closed?

**Comment by gloriajw** [comment] 2022-10-11 11:07
Yes
