### ISSUE TITLE
Weird behavior in email list, weird sorting of names/emails, can't send > 1 email  from same screen without having to refresh because of error.

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#1066] opened 2023-02-15 21:57 UTC
![image](https://user-images.githubusercontent.com/79362/219178813-2f445f71-71bb-4a82-9c25-a31a907b1ae2.png)

Please go here and test. This menu is confusing. Normally menus that work this way: search in one, add to another upon click, have  arrows to designate the direction in which you can add things. Maybe you can add a note: Click in first box to add user to 'To', click in 'To' box to remove user.
Removing users from 'To' throws them in Bcc, which is not making sense to me at all. The cannot be removed from Bcc once there.

It is not possible to send another email afterward without refreshing the screen. Everything is "stuck", and changing users doesn't work.
This isn't behaving well.

**Comment by gloriajw** [comment] 2023-02-15 22:35
OK, so I see the arrows and I figured out how things hop from on panel to the other, and how to make them hop all the way back to remove things from the Bcc. This is a bit confusing, but I get it. There is still an issue when trying to send multiple emails from the same screen with the same selections without changing them.

**Comment by vickis** [comment] 2023-02-15 22:51
Thanks :)

**Comment by tunguyentk** [comment] 2023-02-17 15:09
@gloriajw hi Gloria , I find moving back and forth with the right and left mouse still quite reasonable, it's quite intuitive. But it seems the arrows with no manual are confusing to you. Should I add a manual (or a little popup mess when holding the mouse on the arrow).
As for sending mail , it seems that my clear function is not working with the switch mail table. I have solved it. Everything will return to the original after you finish sending the mail.
But I don't have any problem after sending the mail? I tried it on dev-app and locally , after sending the mail , I still change everything as usual without needing to refresh . Could you please specify the circumstances in which you encountered this error? Thank you so much

**Comment by gloriajw** [comment] 2023-02-17 15:36
Hi @tunguyentk . Thanks for looking at this. I think what is confusing is that you cannot click on individual email addresses to move them out of bcc back to "to". I realize that this can't be done in the 'to' box, because a click moves them forward. But there's nowhere else to go in the bcc box, so clicking on individuals to move them back to "to" in the bcc box would be helpful. 

There is a small help blurb already appearing on that screen. I'll think about how to word it differently to be more helpful. 

Re: sending more than one with the same options, here's what happens:

![image (1)](https://user-images.githubusercontent.com/79362/219697856-c0226bcb-d8bc-4b1b-b1ab-9d51f7281e84.png)

![image (2)](https://user-images.githubusercontent.com/79362/219697813-a580dbe8-1440-424c-a961-cf93e7d0c244.png)

First time is successful. Second time gives me an error. I change nothing, but just add a new subject and click send.

**Comment by tunguyentk** [comment] 2023-02-17 15:54
@gloriajw I understand where the problem is, when you finish sending the email, in fact everything has reset but the interface of the table has not changed, this means that if you press send again it will give an error because There are currently no users in the To column. My full reset solved it.

**Comment by tunguyentk** [comment] 2023-02-17 15:58
@gloriajw About moving between columns, I'm having a hard time understanding what you mean. Because you can move each email with right and left mouse click. When in the Bcc column, just right-click on the email address to be moved and it will return to the "To" column. Am I misunderstanding something?

**Comment by gloriajw** [comment] 2023-02-17 16:05
Hi @tunguyentk . My point was trivial, so please ignore it. If you fix the "clear" bug after email is sent, this will be good enough. We have more important things to fix, so please ignore my navigation request.

**Comment by vickis** [comment] 2023-02-17 19:10
Superb work team
We will document clearly and that should help ensure that users are clear
on how the functions of the email notifications work

Thanks :D

**Comment by helenvarley** [comment] 2023-02-18 11:27
agree, & this is also in the admin section, so general users won't need to know about it, just those who are admins of an UpStage instance. so they will need to be learning a bit more about how things work anyway.

**Comment by tunguyentk** [comment] 2023-02-19 10:05
@gloriajw @helenvarley @vickis Please check, i make the email address table reset when u complete send mail

**Comment by vickis** [comment] 2023-02-19 19:08
great work on the reset :)
thanks!

**Comment by helenvarley** [comment] 2023-02-21 00:34
great! it reset, and the confirmation message persisted until i clicked on the x to close it. thank you! :pray:

**Closed by helenvarley** 2023-02-21 00:34 UTC
