### ISSUE TITLE
guest unable to chat

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#992] opened 2022-07-19 10:03 UTC
one of the walkthrough guests was in the stage but not showing up in the counter (see also other issue) 
 she could access tools as shown in the screengrab - but could not type into chat 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/4249450/179724624-3ace4514-9f66-48ed-aa17-32678f510560.png">

**Comment by vickis** [comment] 2022-07-19 10:07
perhaps related to #973?

**Comment by helenvarley** [comment] 2022-07-19 10:12
the stage is showing as offline (and no left-hand toolbar) so maybe it was a network issue? she did quite soon after this manage to enter the stage and everything was working fine - do you know if she used a different browser? or anything else that could have made a difference?

**Comment by helenvarley** [comment] 2022-07-19 10:22
i don't think this can be an UpStage bug, as nobody else experienced it, and she was then able to log in successfully and the live stage performed as expected. it must have been something at her end.

**Comment by helenvarley** [comment] 2022-08-11 16:48
@vickis - i'm closing this issue, as when the stage is offline you can see and access the tools, but not actually interact, so that will be why she could not chat. the issue is really why she was offline, but as this was only temporary for her, & the rest of us were all live, it is not an UpStage bug.

**Closed by helenvarley** 2022-08-11 16:48 UTC
Labels: bug
